.
.TH vilain 31 "May 2025" "" "Fail2ban-like for OpenBSD"
.SH NAME
vilain \- fail2ban-like for OpenBSD
.
.SH SYNOPSIS
.RS
To use vilain : 
  1. Copy configuration file in /etc/vilain.conf and configure according to your needs.
  2. Configure pf according to the example below
  3. start vilain via rcctl
You only need python >= 3.5 to use it.
.RE

.SH DESCRIPTION
.RS
In pf.conf, add according to your configuration : 

    table <vilain_bruteforce> persist
    block quick from <vilain_bruteforce> 

To see banned IP: 

    vilianctl list-blocked

To unblock a IP:
    
    vilainctl unblock [IP_ADDRESS]

To block a IP:
    
    vliainctl block [IP_ADDRESS]

To see stats:
    
    vilainctl stats
.RE

.SH LOGS
.RS
Watch vilain logs in /var/log/daemon.
.RE


.SH BUGS
.RS
Please let me know : <jhelb1993@gmail.com>
.RE

