#!/bin/sh
# script to launch vilainreport with the latest python3 version available

PYTHON="/usr/local/bin/python3"
if [ -x $PYTHON ]; then
	$PYTHON /usr/local/sbin/vilainreport.py
else
	echo "Error : no python3 executable found"
fi
exit
